<a href="https://colab.research.google.com/github/navrat/EVA_phase1_2022_23/blob/main/pytorch101_codealong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [1]:
import numpy as np
V0 = np.array(1.3)
V1 = np.array([1.,2.,3.])
V2 = np.array([[1.,2.],[4.,5.]])
print(f'{V0}-{V1}-{V2}')

1.3-[1. 2. 3.]-[[1. 2.]
 [4. 5.]]


In [2]:
numpy_array = np.array([1,2,3])

In [3]:
numpy_array.dtype

dtype('int64')

In [4]:
import torch
t1 = torch.Tensor(numpy_array)
# Constructor class which by default does not go to GPU
# !!! ALL tensors below can be derived from the Tensor class above!!!
# copied to a new memory
# We need to force it to go to GPU
# It is an object of Tensor Class - 

In [5]:
t1.dtype

torch.float32

In [6]:
t2 = torch.tensor(numpy_array)
# Factory Function
# produces a new tensor of the same type
# creates a new copy and is directly GPU
# torch.tensor(data, dtype=None, device=None, requires_grad = False/True)
# highly recommended to use this
numpy_array.dtype, t2.dtype 

(dtype('int64'), torch.int64)

In [7]:
t3 = torch.as_tensor(numpy_array)
# Factory Function
# produces a new tensor of the same type
# shares the memory by default unless when GPU is used - then copies.
# Can accept any Python datatype structure including numpy array
# here we have to manually call requires_grad() function 
# highly recommended to use for other data structure
numpy_array.dtype, t3.dtype 

(dtype('int64'), torch.int64)

In [8]:
d = {'k1':1, 'k2':2,'k3':3}
torch.tensor(d) # create key tensor and value tensor separately and then use

RuntimeError: ignored

In [9]:
list(d.values())

[1, 2, 3]

In [10]:
torch.tensor(list(d.values()))

tensor([1, 2, 3])

In [20]:

torch.as_tensor(list(d.keys()))

ValueError: ignored

In [11]:
t4 = torch.from_numpy(numpy_array)
# From numpy
# going to produce a tensor of the same type
# shares the underlying memory with numpy, changing one will change the other
# used to provide 
numpy_array.dtype, t4.dtype

(dtype('int64'), torch.int64)

In [12]:
numpy_array *= 4
numpy_array, t1, t2,t3,t4

(array([ 4,  8, 12]),
 tensor([1., 2., 3.]),
 tensor([1, 2, 3]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]))

In [13]:
t1 *= 4
numpy_array, t1, t2,t3,t4

(array([ 4,  8, 12]),
 tensor([ 4.,  8., 12.]),
 tensor([1, 2, 3]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]))

In [14]:
t2 *= 4
numpy_array, t1, t2,t3,t4

(array([ 4,  8, 12]),
 tensor([ 4.,  8., 12.]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]))

In [15]:
t3 *= 4
numpy_array, t1, t2,t3,t4

(array([16, 32, 48]),
 tensor([ 4.,  8., 12.]),
 tensor([ 4,  8, 12]),
 tensor([16, 32, 48]),
 tensor([16, 32, 48]))

In [16]:
t4 *= 4
numpy_array, t1, t2,t3,t4

(array([ 64, 128, 192]),
 tensor([ 4.,  8., 12.]),
 tensor([ 4,  8, 12]),
 tensor([ 64, 128, 192]),
 tensor([ 64, 128, 192]))

In [17]:
t5 = t4.cuda()
t4.device, t5.device

(device(type='cpu'), device(type='cuda', index=0))

In [18]:
t6 = t4+t5

RuntimeError: ignored

In [19]:
t6 = t4+t3

In [22]:
t = torch.tensor(data = [1,2,3], dtype=torch.float32, 
                 device='cpu',requires_grad=True)

In [23]:
t = torch.as_tensor(data = [1,2,3], dtype=torch.float32, 
                 device='cpu',requires_grad=True)

TypeError: ignored

In [24]:
t = torch.as_tensor(data = [1,2,3], dtype=torch.float32, 
                 device='cpu')
t.requires_grad=True
t

tensor([1., 2., 3.], requires_grad=True)

In [66]:
from torch.autograd import grad
x1 = torch.tensor(2, requires_grad=True, dtype = torch.float16)
x2 = torch.tensor(3, requires_grad=True, dtype = torch.float16)
x3 = torch.tensor(1, requires_grad=True, dtype = torch.float16)
x4 = torch.tensor(4, requires_grad=True, dtype = torch.float16)
x1, x2,x3,x4

(tensor(2., dtype=torch.float16, requires_grad=True),
 tensor(3., dtype=torch.float16, requires_grad=True),
 tensor(1., dtype=torch.float16, requires_grad=True),
 tensor(4., dtype=torch.float16))

In [67]:
z1 = x1*x2
z2 = x3*x4
f = z1 + z2 # f = x1*x2 + x3*x4

In [68]:
f

tensor(10., dtype=torch.float16, grad_fn=<AddBackward0>)

In [69]:
# df/dx1 = x2 # i.e. 3
# df/dx2 = x1 # i.e. 2
# ...
df_dx = grad(outputs = f, inputs = [x1, x2, x3, x4])
print(f'grad of x1 = {df_dx[0]}')
print(f'grad of x2 = {df_dx[1]}')
print(f'grad of x3 = {df_dx[2]}')
print(f'grad of x4 = {df_dx[3]}')


RuntimeError: ignored

In [50]:
# df/dx1 = x2 # i.e. 3
# df/dx2 = x1 # i.e. 2
# ...
## Use of retain_graph =True otherwise we cannot rerun grad!!
df_dx = grad(outputs = f, inputs = [x1, x2, x3, x4], retain_graph=True)
print(f'grad of x1 = {df_dx[0]}')
print(f'grad of x2 = {df_dx[1]}')
print(f'grad of x3 = {df_dx[2]}')
print(f'grad of x4 = {df_dx[3]}')


RuntimeError: ignored

In [65]:
# df/dx1 = x2 # i.e. 3
# df/dx2 = x1 # i.e. 2
# ...
df_dx = grad(outputs = f, inputs = [x1, x2, x3])
print(f'grad of x1 = {df_dx[0]}')
print(f'grad of x2 = {df_dx[1]}')
print(f'grad of x3 = {df_dx[2]}')


grad of x1 = 3.0
grad of x2 = 2.0
grad of x3 = 4.0


In [ ]:
import torch.nn.functional  as F
import torch.optim

opt = optim.SGD(param = [x1,x2,x3,x4], lr=0.001)
opt = optim.zero_grad()

In [61]:
z1 = x1*x2
z2 = x3*x4
f = z1 + z2 # f = x1*x2 + x3*x4

In [64]:
f.backward() # since require_grad is True for all x's. this backward allows for it operate on its own

RuntimeError: ignored

In [63]:
x1.grad, x2.grad, x3.grad, x4.grad

(tensor(3., dtype=torch.float16),
 tensor(2., dtype=torch.float16),
 tensor(4., dtype=torch.float16),
 tensor(1., dtype=torch.float16))

In [72]:
t = torch.randn(6,5)

In [73]:
t.shape, t.size(), len(t.shape) # len of shape is the rank

(torch.Size([6, 5]), torch.Size([6, 5]), 2)

In [75]:
t.numel()

30

In [78]:
t.reshape(1,30) # number of dimensions don't change


tensor([[-0.0034, -1.5348,  0.5479, -0.5260, -0.5817, -0.3634,  0.3089,  2.7336,
          0.7703, -1.7488, -0.8795,  0.7696,  0.9053, -0.9123,  0.8704, -1.3394,
          0.5054, -1.7699,  0.0929,  0.2047, -0.5071, -0.4767,  0.0074, -0.0875,
         -0.1004, -0.4647, -1.1267,  2.0565,  0.5091,  0.9713]])

In [86]:
t.reshape(1,30).size() # number of dimensions don't change


torch.Size([1, 30])

In [88]:
print(t.reshape(1,30).squeeze())
t.reshape(1,30).squeeze().size() # number of dimensions change to 1


tensor([-0.0034, -1.5348,  0.5479, -0.5260, -0.5817, -0.3634,  0.3089,  2.7336,
         0.7703, -1.7488, -0.8795,  0.7696,  0.9053, -0.9123,  0.8704, -1.3394,
         0.5054, -1.7699,  0.0929,  0.2047, -0.5071, -0.4767,  0.0074, -0.0875,
        -0.1004, -0.4647, -1.1267,  2.0565,  0.5091,  0.9713])


torch.Size([30])

In [91]:
print(t.reshape(1,30).squeeze().unsqueeze(dim=0))
t.reshape(1,30).squeeze().unsqueeze(dim=0).size() # re-adding that dimension


tensor([[-0.0034, -1.5348,  0.5479, -0.5260, -0.5817, -0.3634,  0.3089,  2.7336,
          0.7703, -1.7488, -0.8795,  0.7696,  0.9053, -0.9123,  0.8704, -1.3394,
          0.5054, -1.7699,  0.0929,  0.2047, -0.5071, -0.4767,  0.0074, -0.0875,
         -0.1004, -0.4647, -1.1267,  2.0565,  0.5091,  0.9713]])


torch.Size([1, 30])

In [80]:
t.reshape(-1,3) 

tensor([[-0.0034, -1.5348,  0.5479],
        [-0.5260, -0.5817, -0.3634],
        [ 0.3089,  2.7336,  0.7703],
        [-1.7488, -0.8795,  0.7696],
        [ 0.9053, -0.9123,  0.8704],
        [-1.3394,  0.5054, -1.7699],
        [ 0.0929,  0.2047, -0.5071],
        [-0.4767,  0.0074, -0.0875],
        [-0.1004, -0.4647, -1.1267],
        [ 2.0565,  0.5091,  0.9713]])

In [90]:
print(t.reshape(-1,3).squeeze(1))
t.reshape(-1,3).squeeze(1).size() # number of dimensions change to 1


tensor([[-0.0034, -1.5348,  0.5479],
        [-0.5260, -0.5817, -0.3634],
        [ 0.3089,  2.7336,  0.7703],
        [-1.7488, -0.8795,  0.7696],
        [ 0.9053, -0.9123,  0.8704],
        [-1.3394,  0.5054, -1.7699],
        [ 0.0929,  0.2047, -0.5071],
        [-0.4767,  0.0074, -0.0875],
        [-0.1004, -0.4647, -1.1267],
        [ 2.0565,  0.5091,  0.9713]])


torch.Size([10, 3])

In [82]:
t.reshape(-1,2,3)

tensor([[[-0.0034, -1.5348,  0.5479],
         [-0.5260, -0.5817, -0.3634]],

        [[ 0.3089,  2.7336,  0.7703],
         [-1.7488, -0.8795,  0.7696]],

        [[ 0.9053, -0.9123,  0.8704],
         [-1.3394,  0.5054, -1.7699]],

        [[ 0.0929,  0.2047, -0.5071],
         [-0.4767,  0.0074, -0.0875]],

        [[-0.1004, -0.4647, -1.1267],
         [ 2.0565,  0.5091,  0.9713]]])

In [92]:
img1 = torch.randn(4,4)
img2 = torch.randn(4,4)
img3 = torch.randn(4,4)

batch = torch.stack([img1, img2, img3])
batch.shape

torch.Size([3, 4, 4])

In [94]:
batch = batch.reshape(1,3,4,4)
print(batch.shape)
batch

torch.Size([1, 3, 4, 4])


tensor([[[[-1.0349e+00,  3.5358e-01,  4.8504e-02, -8.8829e-01],
          [-4.2766e-02,  1.8128e-01,  1.3507e-01,  1.4103e+00],
          [ 5.0688e-01,  7.5075e-01, -1.0895e+00, -3.0836e-01],
          [ 9.0987e-01,  4.9801e-01, -1.3482e+00, -1.0210e+00]],

         [[ 2.9751e-01, -6.1153e-01,  1.1280e+00, -1.3432e+00],
          [-6.7163e-01, -9.4733e-01,  1.8437e-01,  1.7866e+00],
          [-3.7636e-01, -5.3622e-01,  1.9829e-01, -5.5173e-01],
          [-2.0451e-01,  2.5220e+00,  3.3621e-01,  1.5034e-03]],

         [[ 2.4639e-01, -4.6728e-01,  2.9787e+00,  1.4243e+00],
          [ 6.8470e-01,  2.6644e-03, -4.3196e-01,  1.0354e+00],
          [ 1.7805e+00,  2.6179e-01, -9.8978e-01,  6.6294e-01],
          [ 5.7271e-01, -1.5346e+00,  1.6684e+00, -1.1132e+00]]]])

In [95]:
batch = batch.reshape(-1,3,4,4)
print(batch.shape)
batch

torch.Size([1, 3, 4, 4])


tensor([[[[-1.0349e+00,  3.5358e-01,  4.8504e-02, -8.8829e-01],
          [-4.2766e-02,  1.8128e-01,  1.3507e-01,  1.4103e+00],
          [ 5.0688e-01,  7.5075e-01, -1.0895e+00, -3.0836e-01],
          [ 9.0987e-01,  4.9801e-01, -1.3482e+00, -1.0210e+00]],

         [[ 2.9751e-01, -6.1153e-01,  1.1280e+00, -1.3432e+00],
          [-6.7163e-01, -9.4733e-01,  1.8437e-01,  1.7866e+00],
          [-3.7636e-01, -5.3622e-01,  1.9829e-01, -5.5173e-01],
          [-2.0451e-01,  2.5220e+00,  3.3621e-01,  1.5034e-03]],

         [[ 2.4639e-01, -4.6728e-01,  2.9787e+00,  1.4243e+00],
          [ 6.8470e-01,  2.6644e-03, -4.3196e-01,  1.0354e+00],
          [ 1.7805e+00,  2.6179e-01, -9.8978e-01,  6.6294e-01],
          [ 5.7271e-01, -1.5346e+00,  1.6684e+00, -1.1132e+00]]]])

In [97]:
img1.add(2) # mul, diff, sum(dim=??), mean, prod, std etc.
# .eq(5), .le(), .gt() ...
# .argmin() or .argmax() ; .min() or .max()...
# .flatten()
# all inbuilt and extended from Tensor class


tensor([[0.9651, 2.3536, 2.0485, 1.1117],
        [1.9572, 2.1813, 2.1351, 3.4103],
        [2.5069, 2.7508, 0.9105, 1.6916],
        [2.9099, 2.4980, 0.6518, 0.9790]])

In [ ]:
img1.add(2) # mul, diff etc.

In [ ]:
# Building a neural network

In [ ]:
from torch
import torchvision # provides access to datasets, models, transforms, utility etc.
import torchvision.transforms as transforms

In [ ]:
import pandas as pd
from torch.utils.data import Dataset
class Animals(Dataset):
  def __init__(self, csv_file):
    self.data = pd.read_csv(csv_file)

  # This helps in creating animal_x, animal_label for i in animal_data 
  def __getitem__(self, index):
    r = self.data.iloc[index]
    label, image = r
    return label, image
  
  def __len__(self):
    return len(self.data)

In [98]:
rng = range(10)
next(rng)

TypeError: ignored

In [99]:
rng = iter(range(10))
next(rng)

0

In [100]:
next(rng)

1

In [115]:
import torchvision
train_set = torchvision.datasets.FashionMNIST(
    root = './data'
    ,train=True
    ,download = True
    # , transform = transform.compose
)

  0%|          | 0/26421880 [00:00<?, ?it/s]

Extracting ./data/FashionMNIST/raw/train-images-idx3-ubyte.gz to ./data/FashionMNIST/raw



  0%|          | 0/29515 [00:00<?, ?it/s]

Extracting ./data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to ./data/FashionMNIST/raw



  0%|          | 0/4422102 [00:00<?, ?it/s]

Extracting ./data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to ./data/FashionMNIST/raw



  0%|          | 0/5148 [00:00<?, ?it/s]

Extracting ./data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/FashionMNIST/raw



In [116]:
next(iter(train_set))

(<PIL.Image.Image image mode=L size=28x28 at 0x7FCAE2022DC0>, 9)

In [117]:
i = 1
for j in train_set:
  print(j[1])
  i+=1
  if i>5:
    break
# this allows data to be feteched 1 by 1 

9
0
0
3
0


In [118]:
train_loader = torch.utils.data.DataLoader(
    train_set,
    batch_size = 5,
    shuffle = True
)

In [119]:
next(iter(train_loader))[1]

TypeError: ignored

In [102]:
import numpy as np
import matplotlib.pyplot as plt
torch.set_printoptions(linewidth=120)


In [ ]:
len(train_set)

In [ ]:
train_set.train_labels

In [ ]:
train_set.train_labels.bincount()

In [103]:
sample = next(iter(train_set))
len(sample)

NameError: ignored

In [ ]:
image, label = sample
plt.imshow(image, cmap='grey')
print('label', label)

In [ ]:
# need to squeeze
image, label = sample
plt.imshow(image.squeeze(), cmap='grey')
print('label', label)

In [ ]:
batch = next(iter(train_loader)) # since iter is mentioned again, it starts from the first obs.
len(batch), type(batch)

In [ ]:
images, labels = batch

In [105]:
rng = iter(range(10))
print(next(rng))
print(next(rng))


0
1


In [ ]:
images.shape, labels.shape

In [ ]:
grid = torchvision.

In [ ]:
import torch.nn as nn:

class Network(nn.Module):
  def __init__(self):
    super().__init()
    self.layer = None

    def forward(self, t):
      t = self.layer(t)
      return t

In [107]:
from torch.utils.data import Dataset

class MyDataset(Dataset):
  def __init__(self):
    self.data = (
        "this was an amazing product",
        "this was bad product",
        "amazing product",
        "hard to understand why was it so shitty",
        "good one",
        "i hate it"
    )
  def __getitem__(self, index):
    return self.data[index]
  def __len__(self):
    return len(self.data)

myData = MyDataset()

In [109]:
for m in myData: # leverages __getitem__, __len__. Also can be done by defnining a __iter__()
  print(m)

this was an amazing product
this was bad product
amazing product
hard to understand why was it so shitty
good one
i hate it


In [110]:
train_loader = torch.utils.data.DataLoader(
    myData,
    batch_size = 2,
    shuffle=True
)

In [111]:
for tr in train_loader:
  print(tr)
  

['this was an amazing product', 'i hate it']
['hard to understand why was it so shitty', 'amazing product']
['good one', 'this was bad product']


In [113]:
dir(Dataset)

['__add__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_is_protocol']

In [151]:
class Network(torch.nn.Module):
  def __init__(self):
    super().__init__()
    out_feat_fc1 = 12*20*20
    out_features = 10
    self.out_feat_fc1 = out_feat_fc1
    self.out_features = out_features
    # input 28X28, k =5, RF = 5, output  = 24
    self.conv1 = torch.nn.Conv2d(in_channels = 1, out_channels = 6, kernel_size=5)
    # input 24X24, k=5, RF=9, output = 20
    self.conv2 = torch.nn.Conv2d(in_channels = 6, out_channels = 12, kernel_size=5)
    # input 12*20*20 >> flatten 4800
    # input 4800 >> output 120 (arbitrary for now) = this is out_feat_fc1
    self.fc1 = torch.nn.Linear(in_features = 12*20*20, out_features = self.out_feat_fc1)
    # input 120 >> 10
    self.out = torch.nn.Linear(in_features = self.out_feat_fc1, out_features=self.out_features)

  def forward(self, x):
    # input layer - x
    t_x = x # in case any transformation is done here
    # conv1
    x = self.conv1(x)
    x = F.relu(x)
    x = self.conv2(x)
    x = F.relu(x)
    x = x.reshape(1,-1)
    x = self.fc1(x) # needs a flattened input
    x = F.relu(x)
    x = self.out(x) # needs a flattened input
    return F.Softmax(x)


In [152]:
torch.set_grad_enabled(False)

In [153]:
sample = next(iter(train_set))
image, label = sample 
image # without transform in Dataset class would give image
np.array(image) # need to do a np.array in that case 
# The following with Numpy give a BAD result 
print(np.array(image).shape)
print(torch.tensor(np.array(image)).unsqueeze(0).shape) # to make it a fake batch of one 

(28, 28)
torch.Size([1, 28, 28])


In [ ]:
pred = network(image) ## this will lead to an error because the shape would be 3-D with no notion of batch
pred = network(np.array(image)).unsqueeze(0)) ## this will lead to an error because the shape would be 3-D with no notion of batch

In [154]:
network = Network()
print(network)

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=4800, out_features=4800, bias=True)
  (out): Linear(in_features=4800, out_features=10, bias=True)
)


In [160]:
network(torch.tensor(np.array(image)).unsqueeze(0))

RuntimeError: ignored

In [140]:
network.fc1.weight

Parameter containing:
tensor([[ 0.0021,  0.0081, -0.0016,  ..., -0.0106,  0.0060,  0.0105],
        [ 0.0066, -0.0006,  0.0134,  ...,  0.0096,  0.0022, -0.0106],
        [-0.0002,  0.0006, -0.0142,  ..., -0.0090,  0.0084,  0.0116],
        ...,
        [ 0.0047,  0.0103,  0.0068,  ...,  0.0063, -0.0008,  0.0144],
        [-0.0137, -0.0012, -0.0117,  ...,  0.0009, -0.0077, -0.0019],
        [ 0.0138,  0.0131,  0.0121,  ..., -0.0010, -0.0106,  0.0114]], requires_grad=True)

In [1]:
x = 14
print(id(x))
x *= 2
print(id(x))

11531328
11531776


In [3]:
import torch
x =torch.randn(5, 5) #requires_grad = False by defaults
y =torch.randn(5, 5) #requires_grad = False by defaults
z =torch.randn((5, 5), requires_grad=True)
a = x + y
b = a + z

In [4]:
x,y,z,a,b

(tensor([[ 0.1816,  0.4258, -1.6012,  0.6488,  1.5498],
         [ 1.0985,  1.0772, -1.6264,  0.0475,  0.3091],
         [ 0.3872, -0.4089, -0.9051, -0.7959,  0.0874],
         [-0.0278,  0.6102,  2.4337,  1.0438,  0.4770],
         [-3.1133,  2.0541,  1.2992,  0.5468,  0.2720]]),
 tensor([[-1.7470, -1.8012, -0.7871,  0.2824, -0.0759],
         [-0.6481,  2.1936,  0.2373, -1.1037, -0.1006],
         [-0.2178, -0.5994, -1.1133,  0.8999,  0.7170],
         [ 0.1911, -1.4731, -0.8567, -2.5943, -0.3880],
         [-1.0413, -0.3446,  1.0226, -0.6230, -1.0651]]),
 tensor([[-0.5254,  1.2638,  0.3765,  0.6170,  0.3014],
         [-0.3993, -0.8440, -1.7857, -1.3214, -0.1479],
         [-1.1340,  0.0403, -1.4761,  1.1712,  0.3433],
         [ 0.3284, -0.3249, -0.3398, -0.2264,  0.3052],
         [-0.2806, -0.5607, -0.6998, -0.2877, -0.5417]], requires_grad=True),
 tensor([[-1.5654, -1.3754, -2.3883,  0.9313,  1.4739],
         [ 0.4503,  3.2708, -1.3891, -1.0562,  0.2085],
         [ 0.1694, -1.

In [11]:
torch.randn([9,40,6]).reshape([16,[27,5]])

TypeError: ignored

In [12]:
t = torch.tensor([
    [1, 0, 0, 2],
    [0, 3, 3, 0],
    [4, 0, 0, 5]
], dtype=torch.float32)
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))